import { Colaborador } from './Colaborador.js'
import { Empresa } from './Empresa.js'
import { Socio } from './Socio.js'
import { PagoComprobante } from './PagoComprobante.js'
import { PagoMetodo } from './PagoMetodo.js'
import { Impresora } from './Impresora.js'
import { Caja } from './Caja.js'
import { ProduccionArea } from './ProduccionArea.js'
import { Salon } from './Salon.js'
import { Mesa } from './Mesa.js'
import { ArticuloCategoria } from './ArticuloCategoria.js'
import { Articulo } from './Articulo.js'
import { RecetaInsumo } from './RecetaInsumo.js'
import { ComboArticulo } from './ComboArticulo.js'
import { Transaccion, TransaccionItem } from './Transaccion.js'
import { Kardex } from './Kardex.js'
import { Comprobante, ComprobanteItem } from './Comprobante.js'
import { CajaApertura } from './CajaApertura.js'
import { DineroMovimiento } from './DineroMovimiento.js'